name: JuByteLibraries
version: $VERSION
description: 'Libraries for JuByte-Plugins.'
authors:
  - JuByte
  - Justin_SGD
main: com.jubyte.libraries.JuByteLibraries
libraries:
  - com.h2database:h2:2.3.232